on:
push:
branches:
  - master

jobs:
  build:
    runs-on: ubuntu-22.04

steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Set up Python 3.12
    uses: actions/setup-python@v5
    with:
      python-version: '3.12'

  - name: Install C++ dependencies
    run: |
      sudo apt-get update
      sudo apt-get install -y cmake g++ build-essential

  - name: Run build script
    run: |
      chmod +x build.sh
      ./build.sh

  - name: Upload artifacts
    uses: actions/upload-artifact@v4
    with:
      name: build-artifacts
      path: build/

